name = "Havoc Realms S6"
author = "minecraftbossdj, minecraftbossdj, and minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40c5cd34993882e90f3e7788fc4c312549ff6109fbb2580a84c7744abf1e3f1e"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
